import { sql } from "drizzle-orm";
import {
  check,
  foreignKey,
  index,
  integer,
  primaryKey,
  real,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

// IDs are UUIDs/ULIDs generated by the server. Database defaults use SQLite's
// sortable UTC `YYYY-MM-DD HH:MM:SS` format; application-supplied timestamps
// must use one consistent UTC representation per deployment.
const timestamps = () => ({
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const users = sqliteTable(
  "users",
  {
    id: text("id").primaryKey(),
    role: text("role", { enum: ["admin", "teacher", "student"] }).notNull(),
    username: text("username").notNull(),
    studentNumber: text("student_number"),
    chineseName: text("chinese_name").notNull(),
    englishName: text("english_name"),
    email: text("email"),
    passwordHash: text("password_hash").notNull(),
    mustChangePassword: integer("must_change_password", { mode: "boolean" })
      .notNull()
      .default(true),
    preferredLocale: text("preferred_locale", { enum: ["zh-Hant", "en"] })
      .notNull()
      .default("zh-Hant"),
    status: text("status", { enum: ["active", "suspended", "archived"] })
      .notNull()
      .default("active"),
    failedLoginCount: integer("failed_login_count").notNull().default(0),
    lockedUntil: text("locked_until"),
    lastLoginAt: text("last_login_at"),
    ...timestamps(),
  },
  (table) => [
    uniqueIndex("uq_users_username").on(table.username),
    uniqueIndex("uq_users_student_number").on(table.studentNumber),
    uniqueIndex("uq_users_email").on(table.email),
    index("idx_users_role_status").on(table.role, table.status),
    check("chk_users_role", sql`${table.role} IN ('admin', 'teacher', 'student')`),
    check("chk_users_failed_login_nonnegative", sql`${table.failedLoginCount} >= 0`),
  ],
);

export const authSessions = sqliteTable(
  "auth_sessions",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    tokenHash: text("token_hash").notNull(),
    expiresAt: text("expires_at").notNull(),
    lastSeenAt: text("last_seen_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    revokedAt: text("revoked_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("uq_auth_sessions_token_hash").on(table.tokenHash),
    index("idx_auth_sessions_user_active").on(table.userId, table.revokedAt, table.expiresAt),
    index("idx_auth_sessions_expires_at").on(table.expiresAt),
  ],
);

export const classes = sqliteTable(
  "classes",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    academicYear: text("academic_year").notNull(),
    gradeLevel: text("grade_level"),
    status: text("status", { enum: ["active", "archived"] }).notNull().default("active"),
    createdById: text("created_by_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    ...timestamps(),
  },
  (table) => [
    uniqueIndex("uq_classes_year_name").on(table.academicYear, table.name),
    index("idx_classes_status_year").on(table.status, table.academicYear),
  ],
);

export const classMemberships = sqliteTable(
  "class_memberships",
  {
    classId: text("class_id")
      .notNull()
      .references(() => classes.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    memberRole: text("member_role", { enum: ["teacher", "student"] }).notNull(),
    status: text("status", { enum: ["active", "left", "archived"] })
      .notNull()
      .default("active"),
    joinedAt: text("joined_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    leftAt: text("left_at"),
  },
  (table) => [
    primaryKey({ columns: [table.classId, table.userId] }),
    index("idx_class_memberships_user_status").on(table.userId, table.status),
    index("idx_class_memberships_class_role_status").on(
      table.classId,
      table.memberRole,
      table.status,
    ),
    check(
      "chk_class_memberships_member_role",
      sql`${table.memberRole} IN ('teacher', 'student')`,
    ),
  ],
);

export const courses = sqliteTable(
  "courses",
  {
    id: text("id").primaryKey(),
    ownerTeacherId: text("owner_teacher_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    titleZh: text("title_zh").notNull(),
    titleEn: text("title_en"),
    descriptionZh: text("description_zh"),
    descriptionEn: text("description_en"),
    joinCode: text("join_code"),
    status: text("status", { enum: ["draft", "published", "archived"] })
      .notNull()
      .default("draft"),
    publishedAt: text("published_at"),
    ...timestamps(),
  },
  (table) => [
    uniqueIndex("uq_courses_join_code").on(table.joinCode),
    index("idx_courses_owner_status").on(table.ownerTeacherId, table.status),
  ],
);

export const courseClassAssignments = sqliteTable(
  "course_class_assignments",
  {
    courseId: text("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    classId: text("class_id")
      .notNull()
      .references(() => classes.id, { onDelete: "cascade" }),
    assignedById: text("assigned_by_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    primaryKey({ columns: [table.courseId, table.classId] }),
    index("idx_course_class_assignments_class").on(table.classId),
  ],
);

export const courseEnrollments = sqliteTable(
  "course_enrollments",
  {
    courseId: text("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    studentId: text("student_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    source: text("source", { enum: ["class", "join_code", "manual"] }).notNull(),
    sourceClassId: text("source_class_id").references(() => classes.id, {
      onDelete: "set null",
    }),
    status: text("status", { enum: ["active", "left", "archived"] })
      .notNull()
      .default("active"),
    enrolledAt: text("enrolled_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    leftAt: text("left_at"),
  },
  (table) => [
    primaryKey({ columns: [table.courseId, table.studentId] }),
    index("idx_course_enrollments_student_status").on(table.studentId, table.status),
    index("idx_course_enrollments_course_status").on(table.courseId, table.status),
  ],
);

export const units = sqliteTable(
  "units",
  {
    id: text("id").primaryKey(),
    courseId: text("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    titleZh: text("title_zh").notNull(),
    titleEn: text("title_en"),
    descriptionZh: text("description_zh"),
    descriptionEn: text("description_en"),
    position: integer("position").notNull().default(0),
    status: text("status", { enum: ["draft", "published", "archived"] })
      .notNull()
      .default("draft"),
    publishedAt: text("published_at"),
    ...timestamps(),
  },
  (table) => [
    index("idx_units_course_position").on(table.courseId, table.position),
    index("idx_units_course_status").on(table.courseId, table.status),
  ],
);

export const fileAssets = sqliteTable(
  "file_assets",
  {
    id: text("id").primaryKey(),
    uploadedById: text("uploaded_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    storageKey: text("storage_key").notNull(),
    originalName: text("original_name").notNull(),
    mimeType: text("mime_type").notNull(),
    byteSize: integer("byte_size").notNull(),
    sha256: text("sha256"),
    purpose: text("purpose", { enum: ["material_library", "submission_attachment", "other"] }).notNull().default("other"),
    libraryScope: text("library_scope", { enum: ["private", "school"] }).notNull().default("private"),
    status: text("status", { enum: ["pending", "ready", "quarantined", "deleted"] })
      .notNull()
      .default("pending"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("uq_file_assets_storage_key").on(table.storageKey),
    index("idx_file_assets_uploader_created").on(table.uploadedById, table.createdAt),
    index("idx_file_assets_status_created").on(table.status, table.createdAt),
    index("idx_file_assets_library_available").on(table.purpose, table.status, table.libraryScope),
    index("idx_file_assets_owner_sha").on(table.uploadedById, table.sha256, table.purpose),
    check("chk_file_assets_byte_size_nonnegative", sql`${table.byteSize} >= 0`),
  ],
);

export const materialAssetVersions = sqliteTable(
  "material_asset_versions",
  {
    assetId: text("asset_id")
      .primaryKey()
      .references(() => fileAssets.id, { onDelete: "cascade" }),
    rootAssetId: text("root_asset_id")
      .notNull()
      .references(() => fileAssets.id, { onDelete: "restrict" }),
    previousAssetId: text("previous_asset_id").references(() => fileAssets.id, {
      onDelete: "restrict",
    }),
    versionNumber: integer("version_number").notNull(),
    createdById: text("created_by_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("uq_material_asset_versions_root_number").on(table.rootAssetId, table.versionNumber),
    index("idx_material_asset_versions_root_created").on(table.rootAssetId, table.createdAt),
  ],
);

export const materials = sqliteTable(
  "materials",
  {
    id: text("id").primaryKey(),
    unitId: text("unit_id")
      .notNull()
      .references(() => units.id, { onDelete: "cascade" }),
    createdById: text("created_by_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    fileAssetId: text("file_asset_id").references(() => fileAssets.id, {
      onDelete: "set null",
    }),
    kind: text("kind", {
      enum: ["document", "slides", "web_content", "image", "video_link", "data_file", "archive"],
    }).notNull(),
    titleZh: text("title_zh").notNull(),
    titleEn: text("title_en"),
    bodyZh: text("body_zh"),
    bodyEn: text("body_en"),
    sourceUrl: text("source_url"),
    position: integer("position").notNull().default(0),
    allowDownload: integer("allow_download", { mode: "boolean" }).notNull().default(true),
    assetBindingMode: text("asset_binding_mode", { enum: ["reference", "copy"] })
      .notNull()
      .default("reference"),
    status: text("status", { enum: ["draft", "published", "archived"] })
      .notNull()
      .default("draft"),
    aiReviewStatus: text("ai_review_status", {
      enum: ["not_applicable", "pending_review", "approved", "rejected"],
    })
      .notNull()
      .default("not_applicable"),
    reviewedById: text("reviewed_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    publishedAt: text("published_at"),
    ...timestamps(),
  },
  (table) => [
    index("idx_materials_unit_position").on(table.unitId, table.position),
    index("idx_materials_unit_status").on(table.unitId, table.status),
  ],
);

export const materialConversionJobs = sqliteTable(
  "material_conversion_jobs",
  {
    id: text("id").primaryKey(),
    materialId: text("material_id")
      .notNull()
      .references(() => materials.id, { onDelete: "cascade" }),
    sourceAssetId: text("source_asset_id")
      .notNull()
      .references(() => fileAssets.id, { onDelete: "restrict" }),
    outputAssetId: text("output_asset_id").references(() => fileAssets.id, {
      onDelete: "set null",
    }),
    kind: text("kind", { enum: ["ppt_to_web", "document_preview"] }).notNull(),
    status: text("status", {
      enum: ["queued", "running", "succeeded", "failed"],
    })
      .notNull()
      .default("queued"),
    errorCode: text("error_code"),
    errorMessage: text("error_message"),
    pageCount: integer("page_count"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    startedAt: text("started_at"),
    finishedAt: text("finished_at"),
  },
  (table) => [
    index("idx_material_conversion_jobs_material_created").on(
      table.materialId,
      table.createdAt,
    ),
    index("idx_material_conversion_jobs_status_created").on(table.status, table.createdAt),
  ],
);

export const rubrics = sqliteTable(
  "rubrics",
  {
    id: text("id").primaryKey(),
    ownerTeacherId: text("owner_teacher_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    courseId: text("course_id").references(() => courses.id, { onDelete: "cascade" }),
    titleZh: text("title_zh").notNull(),
    titleEn: text("title_en"),
    status: text("status", { enum: ["draft", "active", "archived"] })
      .notNull()
      .default("draft"),
    ...timestamps(),
  },
  (table) => [
    index("idx_rubrics_owner_status").on(table.ownerTeacherId, table.status),
    index("idx_rubrics_course_status").on(table.courseId, table.status),
  ],
);

export const rubricCriteria = sqliteTable(
  "rubric_criteria",
  {
    id: text("id").primaryKey(),
    rubricId: text("rubric_id")
      .notNull()
      .references(() => rubrics.id, { onDelete: "cascade" }),
    labelZh: text("label_zh").notNull(),
    labelEn: text("label_en"),
    descriptionZh: text("description_zh"),
    descriptionEn: text("description_en"),
    weightPercent: real("weight_percent").notNull(),
    maxScore: real("max_score").notNull(),
    position: integer("position").notNull().default(0),
  },
  (table) => [
    index("idx_rubric_criteria_rubric_position").on(table.rubricId, table.position),
    check(
      "chk_rubric_criteria_weight_range",
      sql`${table.weightPercent} >= 0 AND ${table.weightPercent} <= 100`,
    ),
    check("chk_rubric_criteria_max_score_nonnegative", sql`${table.maxScore} >= 0`),
  ],
);

export const questions = sqliteTable(
  "questions",
  {
    id: text("id").primaryKey(),
    ownerTeacherId: text("owner_teacher_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    courseId: text("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    unitId: text("unit_id").references(() => units.id, { onDelete: "set null" }),
    rubricId: text("rubric_id").references(() => rubrics.id, { onDelete: "set null" }),
    type: text("type", {
      enum: [
        "multiple_choice",
        "fill_blank",
        "short_answer",
        "code_fill",
        "python_code",
        "file_upload",
        "project_upload",
      ],
    }).notNull(),
    titleZh: text("title_zh").notNull(),
    titleEn: text("title_en"),
    promptZh: text("prompt_zh").notNull(),
    promptEn: text("prompt_en"),
    optionsJson: text("options_json"),
    answerKeyJson: text("answer_key_json"),
    explanationZh: text("explanation_zh"),
    explanationEn: text("explanation_en"),
    starterCode: text("starter_code"),
    solutionCode: text("solution_code"),
    requiredConceptsJson: text("required_concepts_json"),
    maxScore: real("max_score").notNull().default(1),
    sharingScope: text("sharing_scope", { enum: ["private", "course", "school"] })
      .notNull()
      .default("private"),
    status: text("status", { enum: ["draft", "published", "archived"] })
      .notNull()
      .default("draft"),
    aiReviewStatus: text("ai_review_status", {
      enum: ["not_applicable", "pending_review", "approved", "rejected"],
    })
      .notNull()
      .default("not_applicable"),
    reviewedById: text("reviewed_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    ...timestamps(),
  },
  (table) => [
    uniqueIndex("uq_questions_id_course").on(table.id, table.courseId),
    index("idx_questions_course_status").on(table.courseId, table.status),
    index("idx_questions_owner_status").on(table.ownerTeacherId, table.status),
    index("idx_questions_unit_status").on(table.unitId, table.status),
    index("idx_questions_scope_status").on(table.sharingScope, table.status),
    check("chk_questions_max_score_nonnegative", sql`${table.maxScore} >= 0`),
  ],
);

export const testCases = sqliteTable(
  "test_cases",
  {
    id: text("id").primaryKey(),
    questionId: text("question_id")
      .notNull()
      .references(() => questions.id, { onDelete: "cascade" }),
    visibility: text("visibility", { enum: ["public", "hidden"] }).notNull(),
    label: text("label"),
    inputJson: text("input_json"),
    expectedOutput: text("expected_output").notNull(),
    comparisonMode: text("comparison_mode", {
      enum: ["exact", "trimmed", "numeric_tolerance"],
    })
      .notNull()
      .default("trimmed"),
    tolerance: real("tolerance"),
    weight: real("weight").notNull().default(1),
    position: integer("position").notNull().default(0),
    timeLimitMs: integer("time_limit_ms"),
    memoryLimitMb: integer("memory_limit_mb"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("uq_test_cases_id_question").on(table.id, table.questionId),
    index("idx_test_cases_question_visibility_position").on(
      table.questionId,
      table.visibility,
      table.position,
    ),
    check("chk_test_cases_visibility", sql`${table.visibility} IN ('public', 'hidden')`),
    check("chk_test_cases_weight_nonnegative", sql`${table.weight} >= 0`),
  ],
);

export const assignments = sqliteTable(
  "assignments",
  {
    id: text("id").primaryKey(),
    courseId: text("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    unitId: text("unit_id").references(() => units.id, { onDelete: "set null" }),
    createdById: text("created_by_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    kind: text("kind", { enum: ["practice", "homework", "quiz", "exam"] })
      .notNull()
      .default("homework"),
    titleZh: text("title_zh").notNull(),
    titleEn: text("title_en"),
    instructionsZh: text("instructions_zh"),
    instructionsEn: text("instructions_en"),
    publishAt: text("publish_at"),
    dueAt: text("due_at"),
    answerReleaseAt: text("answer_release_at"),
    maxAttempts: integer("max_attempts").notNull().default(1),
    allowLate: integer("allow_late", { mode: "boolean" }).notNull().default(false),
    allowResubmit: integer("allow_resubmit", { mode: "boolean" }).notNull().default(false),
    randomizeOrder: integer("randomize_order", { mode: "boolean" }).notNull().default(false),
    questionSelectionCount: integer("question_selection_count"),
    showScoreImmediately: integer("show_score_immediately", { mode: "boolean" })
      .notNull()
      .default(true),
    showTestResultsImmediately: integer("show_test_results_immediately", { mode: "boolean" })
      .notNull()
      .default(true),
    aiAssistantEnabled: integer("ai_assistant_enabled", { mode: "boolean" })
      .notNull()
      .default(true),
    status: text("status", { enum: ["draft", "scheduled", "published", "closed", "archived"] })
      .notNull()
      .default("draft"),
    ...timestamps(),
  },
  (table) => [
    uniqueIndex("uq_assignments_id_course").on(table.id, table.courseId),
    index("idx_assignments_course_status_publish").on(
      table.courseId,
      table.status,
      table.publishAt,
    ),
    index("idx_assignments_course_due").on(table.courseId, table.dueAt),
    index("idx_assignments_unit").on(table.unitId),
    check("chk_assignments_max_attempts_positive", sql`${table.maxAttempts} > 0`),
    check(
      "chk_assignments_selection_count_positive",
      sql`${table.questionSelectionCount} IS NULL OR ${table.questionSelectionCount} > 0`,
    ),
  ],
);

export const assignmentItems = sqliteTable(
  "assignment_items",
  {
    assignmentId: text("assignment_id").notNull(),
    questionId: text("question_id").notNull(),
    courseId: text("course_id").notNull(),
    position: integer("position").notNull().default(0),
    scoreOverride: real("score_override"),
  },
  (table) => [
    primaryKey({ columns: [table.assignmentId, table.questionId] }),
    foreignKey({
      name: "fk_assignment_items_assignment_course",
      columns: [table.assignmentId, table.courseId],
      foreignColumns: [assignments.id, assignments.courseId],
    }).onDelete("cascade"),
    foreignKey({
      name: "fk_assignment_items_question_course",
      columns: [table.questionId, table.courseId],
      foreignColumns: [questions.id, questions.courseId],
    }).onDelete("restrict"),
    uniqueIndex("uq_assignment_items_assignment_position").on(
      table.assignmentId,
      table.position,
    ),
    check("chk_assignment_items_position_nonnegative", sql`${table.position} >= 0`),
    check(
      "chk_assignment_items_score_override_nonnegative",
      sql`${table.scoreOverride} IS NULL OR ${table.scoreOverride} >= 0`,
    ),
  ],
);

export const submissions = sqliteTable(
  "submissions",
  {
    id: text("id").primaryKey(),
    assignmentId: text("assignment_id")
      .notNull()
      .references(() => assignments.id, { onDelete: "cascade" }),
    studentId: text("student_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    attemptNumber: integer("attempt_number").notNull(),
    status: text("status", { enum: ["draft", "submitted", "grading", "graded", "returned"] })
      .notNull()
      .default("draft"),
    startedAt: text("started_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    submittedAt: text("submitted_at"),
    isLate: integer("is_late", { mode: "boolean" }).notNull().default(false),
    lastActivityAt: text("last_activity_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("uq_submissions_id_assignment_student").on(
      table.id,
      table.assignmentId,
      table.studentId,
    ),
    uniqueIndex("uq_submissions_assignment_student_attempt").on(
      table.assignmentId,
      table.studentId,
      table.attemptNumber,
    ),
    index("idx_submissions_assignment_status").on(table.assignmentId, table.status),
    index("idx_submissions_student_status_activity").on(
      table.studentId,
      table.status,
      table.lastActivityAt,
    ),
    check("chk_submissions_attempt_positive", sql`${table.attemptNumber} > 0`),
  ],
);

export const submissionAnswers = sqliteTable(
  "submission_answers",
  {
    id: text("id").primaryKey(),
    submissionId: text("submission_id").notNull(),
    assignmentId: text("assignment_id").notNull(),
    studentId: text("student_id").notNull(),
    questionId: text("question_id").notNull(),
    questionSnapshotJson: text("question_snapshot_json").notNull().default("{}"),
    // Creating these rows when a draft starts freezes randomized selections/order.
    position: integer("position").notNull().default(0),
    answerText: text("answer_text"),
    answerJson: text("answer_json"),
    fileAssetId: text("file_asset_id").references(() => fileAssets.id, {
      onDelete: "set null",
    }),
    autoScore: real("auto_score"),
    aiSuggestedScore: real("ai_suggested_score"),
    teacherScore: real("teacher_score"),
    finalScore: real("final_score"),
    teacherFeedback: text("teacher_feedback"),
    aiFeedback: text("ai_feedback"),
    reviewStatus: text("review_status", {
      enum: ["not_required", "pending", "confirmed", "adjusted"],
    })
      .notNull()
      .default("not_required"),
    reviewedById: text("reviewed_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    reviewedAt: text("reviewed_at"),
    ...timestamps(),
  },
  (table) => [
    foreignKey({
      name: "fk_submission_answers_submission_assignment_student",
      columns: [table.submissionId, table.assignmentId, table.studentId],
      foreignColumns: [submissions.id, submissions.assignmentId, submissions.studentId],
    }).onDelete("cascade"),
    foreignKey({
      name: "fk_submission_answers_assignment_question",
      columns: [table.assignmentId, table.questionId],
      foreignColumns: [assignmentItems.assignmentId, assignmentItems.questionId],
    }).onDelete("restrict"),
    uniqueIndex("uq_submission_answers_submission_question").on(
      table.submissionId,
      table.questionId,
    ),
    uniqueIndex("uq_submission_answers_id_student").on(table.id, table.studentId),
    uniqueIndex("uq_submission_answers_id_question").on(table.id, table.questionId),
    index("idx_submission_answers_submission_position").on(table.submissionId, table.position),
    index("idx_submission_answers_question_review").on(table.questionId, table.reviewStatus),
  ],
);

export const codeSnapshots = sqliteTable(
  "code_snapshots",
  {
    id: text("id").primaryKey(),
    submissionAnswerId: text("submission_answer_id").notNull(),
    studentId: text("student_id").notNull(),
    sequenceNumber: integer("sequence_number").notNull(),
    source: text("source", { enum: ["autosave", "run", "submit", "paste"] }).notNull(),
    code: text("code").notNull(),
    sha256: text("sha256").notNull().default(""),
    pastedCharacterCount: integer("pasted_character_count").notNull().default(0),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    foreignKey({
      name: "fk_code_snapshots_answer_student",
      columns: [table.submissionAnswerId, table.studentId],
      foreignColumns: [submissionAnswers.id, submissionAnswers.studentId],
    }).onDelete("cascade"),
    uniqueIndex("uq_code_snapshots_id_answer").on(table.id, table.submissionAnswerId),
    uniqueIndex("uq_code_snapshots_answer_sequence").on(
      table.submissionAnswerId,
      table.sequenceNumber,
    ),
    index("idx_code_snapshots_answer_created").on(table.submissionAnswerId, table.createdAt),
    index("idx_code_snapshots_student_created").on(table.studentId, table.createdAt),
    check(
      "chk_code_snapshots_pasted_characters_nonnegative",
      sql`${table.pastedCharacterCount} >= 0`,
    ),
  ],
);

export const codeRuns = sqliteTable(
  "code_runs",
  {
    id: text("id").primaryKey(),
    submissionAnswerId: text("submission_answer_id").notNull(),
    actorId: text("actor_id").references(() => users.id, { onDelete: "set null" }),
    studentId: text("student_id").notNull().default(""),
    snapshotId: text("snapshot_id").notNull(),
    questionId: text("question_id").notNull(),
    runType: text("run_type", { enum: ["execute", "grade"] }).notNull(),
    status: text("status", { enum: ["queued", "running", "passed", "failed", "timeout", "error"] })
      .notNull()
      .default("queued"),
    stdout: text("stdout"),
    stderr: text("stderr"),
    exitCode: integer("exit_code"),
    durationMs: integer("duration_ms"),
    peakMemoryKb: integer("peak_memory_kb"),
    runnerVersion: text("runner_version").notNull().default("unknown"),
    runnerImage: text("runner_image").notNull().default("unknown"),
    limitsJson: text("limits_json").notNull().default("{}"),
    codeSha256: text("code_sha256").notNull().default(""),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    startedAt: text("started_at"),
    finishedAt: text("finished_at"),
  },
  (table) => [
    foreignKey({
      name: "fk_code_runs_answer_question",
      columns: [table.submissionAnswerId, table.questionId],
      foreignColumns: [submissionAnswers.id, submissionAnswers.questionId],
    }).onDelete("cascade"),
    foreignKey({
      name: "fk_code_runs_snapshot_answer",
      columns: [table.snapshotId, table.submissionAnswerId],
      foreignColumns: [codeSnapshots.id, codeSnapshots.submissionAnswerId],
    }).onDelete("restrict"),
    uniqueIndex("uq_code_runs_id_question").on(table.id, table.questionId),
    index("idx_code_runs_answer_created").on(table.submissionAnswerId, table.createdAt),
    index("idx_code_runs_snapshot").on(table.snapshotId),
    index("idx_code_runs_status_created").on(table.status, table.createdAt),
  ],
);

export const testResults = sqliteTable(
  "test_results",
  {
    id: text("id").primaryKey(),
    codeRunId: text("code_run_id").notNull(),
    testCaseId: text("test_case_id").notNull(),
    questionId: text("question_id").notNull(),
    testCaseSnapshotJson: text("test_case_snapshot_json").notNull().default("{}"),
    status: text("status", { enum: ["passed", "failed", "timeout", "error"] }).notNull(),
    actualOutput: text("actual_output"),
    errorMessage: text("error_message"),
    durationMs: integer("duration_ms"),
    peakMemoryKb: integer("peak_memory_kb"),
    scoreAwarded: real("score_awarded").notNull().default(0),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    foreignKey({
      name: "fk_test_results_run_question",
      columns: [table.codeRunId, table.questionId],
      foreignColumns: [codeRuns.id, codeRuns.questionId],
    }).onDelete("cascade"),
    foreignKey({
      name: "fk_test_results_case_question",
      columns: [table.testCaseId, table.questionId],
      foreignColumns: [testCases.id, testCases.questionId],
    }).onDelete("restrict"),
    uniqueIndex("uq_test_results_run_case").on(table.codeRunId, table.testCaseId),
    index("idx_test_results_run_status").on(table.codeRunId, table.status),
  ],
);

export const grades = sqliteTable(
  "grades",
  {
    id: text("id").primaryKey(),
    submissionId: text("submission_id")
      .notNull()
      .references(() => submissions.id, { onDelete: "cascade" }),
    autoScore: real("auto_score"),
    aiSuggestedScore: real("ai_suggested_score"),
    teacherAdjustedScore: real("teacher_adjusted_score"),
    finalScore: real("final_score"),
    maxScore: real("max_score").notNull(),
    status: text("status", { enum: ["pending", "review_required", "confirmed", "released"] })
      .notNull()
      .default("pending"),
    gradedById: text("graded_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    teacherComment: text("teacher_comment"),
    gradedAt: text("graded_at"),
    releasedAt: text("released_at"),
    ...timestamps(),
  },
  (table) => [
    uniqueIndex("uq_grades_submission").on(table.submissionId),
    index("idx_grades_status_released").on(table.status, table.releasedAt),
    check("chk_grades_max_score_nonnegative", sql`${table.maxScore} >= 0`),
  ],
);

export const learningSessions = sqliteTable(
  "learning_sessions",
  {
    id: text("id").primaryKey(),
    studentId: text("student_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    courseId: text("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    assignmentId: text("assignment_id").references(() => assignments.id, {
      onDelete: "set null",
    }),
    startedAt: text("started_at").notNull(),
    endedAt: text("ended_at"),
    activeSeconds: integer("active_seconds").notNull().default(0),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("idx_learning_sessions_student_started").on(table.studentId, table.startedAt),
    index("idx_learning_sessions_course_started").on(table.courseId, table.startedAt),
    check("chk_learning_sessions_active_nonnegative", sql`${table.activeSeconds} >= 0`),
  ],
);

export const classroomSessions = sqliteTable(
  "classroom_sessions",
  {
    id: text("id").primaryKey(),
    courseId: text("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    createdById: text("created_by_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    title: text("title").notNull(),
    status: text("status", { enum: ["active", "ended", "archived"] })
      .notNull()
      .default("active"),
    version: integer("version").notNull().default(0),
    startedAt: text("started_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    endedAt: text("ended_at"),
    ...timestamps(),
  },
  (table) => [
    index("idx_classroom_sessions_course_status").on(table.courseId, table.status),
    index("idx_classroom_sessions_created").on(table.createdById, table.createdAt),
  ],
);

export const classroomActivities = sqliteTable(
  "classroom_activities",
  {
    id: text("id").primaryKey(),
    sessionId: text("session_id")
      .notNull()
      .references(() => classroomSessions.id, { onDelete: "cascade" }),
    courseId: text("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    assignmentId: text("assignment_id").references(() => assignments.id, {
      onDelete: "set null",
    }),
    createdById: text("created_by_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    title: text("title").notNull(),
    promptJson: text("prompt_json"),
    status: text("status", {
      enum: ["draft", "active", "paused", "locked", "reopened", "ended"],
    })
      .notNull()
      .default("draft"),
    version: integer("version").notNull().default(0),
    anonymousAnswers: integer("anonymous_answers", { mode: "boolean" })
      .notNull()
      .default(true),
    startedAt: text("started_at"),
    endedAt: text("ended_at"),
    ...timestamps(),
  },
  (table) => [
    index("idx_classroom_activities_session_status").on(table.sessionId, table.status),
    index("idx_classroom_activities_assignment_status").on(table.assignmentId, table.status),
  ],
);

export const classroomParticipants = sqliteTable(
  "classroom_participants",
  {
    sessionId: text("session_id")
      .notNull()
      .references(() => classroomSessions.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    participantRole: text("participant_role", { enum: ["teacher", "student"] }).notNull(),
    status: text("status", { enum: ["active", "left"] }).notNull().default("active"),
    lastSeenAt: text("last_seen_at"),
    joinedAt: text("joined_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    primaryKey({ columns: [table.sessionId, table.userId] }),
    index("idx_classroom_participants_session_status").on(table.sessionId, table.status),
    index("idx_classroom_participants_user_status").on(table.userId, table.status),
  ],
);

export const classroomEvents = sqliteTable(
  "classroom_events",
  {
    id: text("id").primaryKey(),
    sessionId: text("session_id")
      .notNull()
      .references(() => classroomSessions.id, { onDelete: "cascade" }),
    activityId: text("activity_id").references(() => classroomActivities.id, {
      onDelete: "set null",
    }),
    version: integer("version").notNull(),
    eventType: text("event_type").notNull(),
    actorId: text("actor_id").references(() => users.id, { onDelete: "set null" }),
    idempotencyKey: text("idempotency_key").notNull(),
    payloadJson: text("payload_json").notNull().default("{}"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("uq_classroom_events_session_idempotency").on(table.sessionId, table.idempotencyKey),
    uniqueIndex("uq_classroom_events_session_version").on(table.sessionId, table.version),
    index("idx_classroom_events_session_version").on(table.sessionId, table.version),
  ],
);

export const aiProviderConfigs = sqliteTable(
  "ai_provider_configs",
  {
    id: text("id").primaryKey(),
    providerKey: text("provider_key").notNull(),
    displayName: text("display_name").notNull(),
    apiBaseUrl: text("api_base_url"),
    apiPath: text("api_path").notNull().default("/chat/completions"),
    timeoutMs: integer("timeout_ms").notNull().default(15000),
    defaultModel: text("default_model").notNull(),
    encryptedApiKey: text("encrypted_api_key").notNull(),
    apiKeyHint: text("api_key_hint"),
    encryptionVersion: integer("encryption_version").notNull().default(1),
    keyRotatedAt: text("key_rotated_at"),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(false),
    createdById: text("created_by_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    updatedById: text("updated_by_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    ...timestamps(),
  },
  (table) => [
    uniqueIndex("uq_ai_provider_configs_provider_key").on(table.providerKey),
    check("chk_ai_provider_timeout", sql`${table.timeoutMs} BETWEEN 1000 AND 120000`),
  ],
);

export const aiSettings = sqliteTable(
  "ai_settings",
  {
    id: text("id").primaryKey().default("global"),
    providerConfigId: text("provider_config_id").references(() => aiProviderConfigs.id, {
      onDelete: "set null",
    }),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(false),
    assistantMode: text("assistant_mode", {
      enum: ["hints_only", "progressive", "full_after_attempts"],
    })
      .notNull()
      .default("hints_only"),
    fullAnswerAfterAttempts: integer("full_answer_after_attempts"),
    schoolDailyTokenLimit: integer("school_daily_token_limit"),
    schoolDailyRequestLimit: integer("school_daily_request_limit"),
    studentDailyTokenLimit: integer("student_daily_token_limit"),
    studentDailyRequestLimit: integer("student_daily_request_limit"),
    timezone: text("timezone").notNull().default("Asia/Macau"),
    saveConversations: integer("save_conversations", { mode: "boolean" })
      .notNull()
      .default(true),
    conversationRetentionDays: integer("conversation_retention_days"),
    maxHintLayers: integer("max_hint_layers").notNull().default(3),
    updatedById: text("updated_by_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    ...timestamps(),
  },
  (table) => [
    check("chk_ai_settings_singleton", sql`${table.id} = 'global'`),
    check(
      "chk_ai_settings_attempts_positive",
      sql`${table.fullAnswerAfterAttempts} IS NULL OR ${table.fullAnswerAfterAttempts} > 0`,
    ),
  ],
);

export const questionHints = sqliteTable(
  "question_hints",
  {
    id: text("id").primaryKey(),
    questionId: text("question_id").notNull().references(() => questions.id, { onDelete: "cascade" }),
    level: integer("level").notNull(),
    contentZh: text("content_zh").notNull(),
    contentEn: text("content_en"),
    source: text("source", { enum: ["manual", "ai"] }).notNull().default("manual"),
    status: text("status", { enum: ["draft", "approved", "rejected"] }).notNull().default("draft"),
    createdById: text("created_by_id").notNull().references(() => users.id, { onDelete: "restrict" }),
    reviewedById: text("reviewed_by_id").references(() => users.id, { onDelete: "set null" }),
    reviewedAt: text("reviewed_at"),
    ...timestamps(),
  },
  (table) => [
    uniqueIndex("uq_question_hints_question_level").on(table.questionId, table.level),
    index("idx_question_hints_question_status").on(table.questionId, table.status),
    check("chk_question_hints_level_positive", sql`${table.level} BETWEEN 1 AND 3`),
  ],
);

export const studentHintUnlocks = sqliteTable(
  "student_hint_unlocks",
  {
    id: text("id").primaryKey(),
    studentId: text("student_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    submissionId: text("submission_id").notNull().references(() => submissions.id, { onDelete: "cascade" }),
    questionId: text("question_id").notNull().references(() => questions.id, { onDelete: "cascade" }),
    hintId: text("hint_id").notNull().references(() => questionHints.id, { onDelete: "restrict" }),
    level: integer("level").notNull(),
    source: text("source", { enum: ["manual", "ai"] }).notNull(),
    idempotencyKey: text("idempotency_key").notNull(),
    unlockedAt: text("unlocked_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("uq_student_hint_unlock_level").on(table.studentId, table.submissionId, table.questionId, table.level),
    uniqueIndex("uq_student_hint_unlock_idempotency").on(table.studentId, table.idempotencyKey),
    index("idx_student_hint_unlock_question_time").on(table.questionId, table.unlockedAt),
  ],
);

export const aiConversations = sqliteTable(
  "ai_conversations",
  {
    id: text("id").primaryKey(),
    studentId: text("student_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    courseId: text("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    assignmentId: text("assignment_id"),
    questionId: text("question_id"),
    status: text("status", { enum: ["active", "closed", "deleted"] })
      .notNull()
      .default("active"),
    startedAt: text("started_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    lastMessageAt: text("last_message_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    foreignKey({
      name: "fk_ai_conversations_active_enrollment",
      columns: [table.courseId, table.studentId],
      foreignColumns: [courseEnrollments.courseId, courseEnrollments.studentId],
    }).onDelete("cascade"),
    foreignKey({
      name: "fk_ai_conversations_assignment_course",
      columns: [table.assignmentId, table.courseId],
      foreignColumns: [assignments.id, assignments.courseId],
    }).onDelete("cascade"),
    foreignKey({
      name: "fk_ai_conversations_question_course",
      columns: [table.questionId, table.courseId],
      foreignColumns: [questions.id, questions.courseId],
    }).onDelete("cascade"),
    index("idx_ai_conversations_student_recent").on(table.studentId, table.lastMessageAt),
    index("idx_ai_conversations_course_recent").on(table.courseId, table.lastMessageAt),
    index("idx_ai_conversations_assignment_student").on(table.assignmentId, table.studentId),
  ],
);

export const aiMessages = sqliteTable(
  "ai_messages",
  {
    id: text("id").primaryKey(),
    conversationId: text("conversation_id")
      .notNull()
      .references(() => aiConversations.id, { onDelete: "cascade" }),
    role: text("role", { enum: ["system", "student", "assistant", "teacher"] }).notNull(),
    content: text("content").notNull(),
    sequenceNumber: integer("sequence_number").notNull(),
    promptVersion: text("prompt_version"),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    uniqueIndex("uq_ai_messages_conversation_sequence").on(
      table.conversationId,
      table.sequenceNumber,
    ),
    index("idx_ai_messages_conversation_created").on(table.conversationId, table.createdAt),
  ],
);

export const aiUsage = sqliteTable(
  "ai_usage",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    providerConfigId: text("provider_config_id").references(() => aiProviderConfigs.id, {
      onDelete: "set null",
    }),
    conversationId: text("conversation_id").references(() => aiConversations.id, {
      onDelete: "set null",
    }),
    purpose: text("purpose", {
      enum: ["student_hint", "translation", "question_generation", "grading", "summary", "feedback"],
    }).notNull(),
    usageDate: text("usage_date").notNull(),
    model: text("model").notNull(),
    inputTokens: integer("input_tokens").notNull().default(0),
    outputTokens: integer("output_tokens").notNull().default(0),
    latencyMs: integer("latency_ms"),
    status: text("status", { enum: ["success", "rejected", "error"] }).notNull(),
    errorCode: text("error_code"),
    reservationId: text("reservation_id"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("idx_ai_usage_date").on(table.usageDate),
    index("idx_ai_usage_user_date").on(table.userId, table.usageDate),
    index("idx_ai_usage_provider_date").on(table.providerConfigId, table.usageDate),
    index("idx_ai_usage_conversation_created").on(table.conversationId, table.createdAt),
    check(
      "chk_ai_usage_tokens_nonnegative",
      sql`${table.inputTokens} >= 0 AND ${table.outputTokens} >= 0`,
    ),
  ],
);

// Reserve quota in a transaction before calling a provider. The server must use
// an atomic INSERT ... ON CONFLICT DO UPDATE with limit predicates, then settle
// the reservation and append the immutable ai_usage event.
export const aiDailyQuotas = sqliteTable(
  "ai_daily_quotas",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    usageDate: text("usage_date").notNull(),
    reservedRequests: integer("reserved_requests").notNull().default(0),
    completedRequests: integer("completed_requests").notNull().default(0),
    reservedTokens: integer("reserved_tokens").notNull().default(0),
    usedTokens: integer("used_tokens").notNull().default(0),
    updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.usageDate] }),
    index("idx_ai_daily_quotas_date").on(table.usageDate),
    check(
      "chk_ai_daily_quotas_nonnegative",
      sql`${table.reservedRequests} >= 0 AND ${table.completedRequests} >= 0 AND ${table.reservedTokens} >= 0 AND ${table.usedTokens} >= 0`,
    ),
  ],
);

export const aiReservations = sqliteTable(
  "ai_reservations",
  {
    id: text("id").primaryKey(),
    reservationKey: text("reservation_key").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    providerConfigId: text("provider_config_id").references(() => aiProviderConfigs.id, {
      onDelete: "set null",
    }),
    usageDate: text("usage_date").notNull(),
    reservedRequests: integer("reserved_requests").notNull().default(1),
    reservedTokens: integer("reserved_tokens").notNull().default(0),
    status: text("status", { enum: ["reserved", "settled", "rolled_back"] })
      .notNull()
      .default("reserved"),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    createdAt: text("created_at").notNull(),
    settledAt: text("settled_at"),
  },
  (table) => [
    uniqueIndex("uq_ai_reservations_key").on(table.reservationKey),
    index("idx_ai_reservations_user_date").on(table.userId, table.usageDate),
  ],
);

export const aiSchoolDailyQuotas = sqliteTable(
  "ai_school_daily_quotas",
  {
    usageDate: text("usage_date").primaryKey(),
    reservedRequests: integer("reserved_requests").notNull().default(0),
    completedRequests: integer("completed_requests").notNull().default(0),
    reservedTokens: integer("reserved_tokens").notNull().default(0),
    usedTokens: integer("used_tokens").notNull().default(0),
    updatedAt: text("updated_at").notNull(),
  },
  (table) => [
    index("idx_ai_school_daily_quotas_date").on(table.usageDate),
  ],
);

export const aiArtifacts = sqliteTable(
  "ai_artifacts",
  {
    id: text("id").primaryKey(),
    artifactType: text("artifact_type", {
      enum: ["material", "translation", "question", "feedback", "suggested_score"],
    }).notNull(),
    courseId: text("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    studentId: text("student_id").references(() => users.id, { onDelete: "set null" }),
    materialId: text("material_id").references(() => materials.id, { onDelete: "set null" }),
    questionId: text("question_id").references(() => questions.id, { onDelete: "set null" }),
    submissionAnswerId: text("submission_answer_id").references(() => submissionAnswers.id, { onDelete: "set null" }),
    contentJson: text("content_json").notNull(),
    status: text("status", { enum: ["draft", "pending_review", "approved", "rejected", "published"] })
      .notNull()
      .default("pending_review"),
    createdById: text("created_by_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    reviewedById: text("reviewed_by_id").references(() => users.id, { onDelete: "set null" }),
    reviewComment: text("review_comment"),
    reviewedAt: text("reviewed_at"),
    publishedAt: text("published_at"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (table) => [
    index("idx_ai_artifacts_course_status").on(table.courseId, table.status),
    index("idx_ai_artifacts_target_status").on(table.studentId, table.status),
  ],
);

export const announcements = sqliteTable(
  "announcements",
  {
    id: text("id").primaryKey(),
    authorId: text("author_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    courseId: text("course_id").references(() => courses.id, { onDelete: "cascade" }),
    classId: text("class_id").references(() => classes.id, { onDelete: "cascade" }),
    titleZh: text("title_zh").notNull(),
    titleEn: text("title_en"),
    bodyZh: text("body_zh").notNull(),
    bodyEn: text("body_en"),
    status: text("status", { enum: ["draft", "published", "archived"] })
      .notNull()
      .default("draft"),
    publishAt: text("publish_at"),
    expiresAt: text("expires_at"),
    ...timestamps(),
  },
  (table) => [
    index("idx_announcements_course_publish").on(table.courseId, table.status, table.publishAt),
    index("idx_announcements_class_publish").on(table.classId, table.status, table.publishAt),
    check(
      "chk_announcements_has_audience",
      sql`${table.courseId} IS NOT NULL OR ${table.classId} IS NOT NULL`,
    ),
  ],
);

export const notifications = sqliteTable(
  "notifications",
  {
    id: text("id").primaryKey(),
    recipientId: text("recipient_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    announcementId: text("announcement_id").references(() => announcements.id, {
      onDelete: "cascade",
    }),
    type: text("type", {
      enum: ["announcement", "assignment_published", "due_reminder", "late_notice", "grade_released", "system"],
    }).notNull(),
    title: text("title").notNull(),
    body: text("body"),
    linkPath: text("link_path"),
    sourceKey: text("source_key").notNull().default(""),
    readAt: text("read_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("idx_notifications_recipient_created").on(table.recipientId, table.createdAt),
    index("idx_notifications_recipient_unread")
      .on(table.recipientId, table.createdAt)
      .where(sql`${table.readAt} IS NULL`),
    uniqueIndex("uq_notifications_recipient_source").on(table.recipientId, table.sourceKey),
  ],
);

export const emailDeliveries = sqliteTable(
  "email_deliveries",
  {
    id: text("id").primaryKey(),
    notificationId: text("notification_id")
      .notNull()
      .references(() => notifications.id, { onDelete: "cascade" }),
    recipientEmail: text("recipient_email").notNull(),
    status: text("status", { enum: ["queued", "sending", "sent", "failed", "suppressed", "cancelled", "bounced"] })
      .notNull()
      .default("queued"),
    providerMessageId: text("provider_message_id"),
    subject: text("subject"),
    body: text("body"),
    attemptCount: integer("attempt_count").notNull().default(0),
    nextAttemptAt: text("next_attempt_at"),
    lastErrorCode: text("last_error_code"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    sentAt: text("sent_at"),
    cancelledAt: text("cancelled_at"),
    bouncedAt: text("bounced_at"),
  },
  (table) => [
    uniqueIndex("uq_email_deliveries_notification").on(table.notificationId),
    index("idx_email_deliveries_status_next_attempt").on(table.status, table.nextAttemptAt),
  ],
);

export const featureFlags = sqliteTable("feature_flags", {
  key: text("key").primaryKey(),
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(false),
  configJson: text("config_json"),
  updatedById: text("updated_by_id")
    .notNull()
    .references(() => users.id, { onDelete: "restrict" }),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const systemSettings = sqliteTable("system_settings", {
  key: text("key").primaryKey(),
  valueJson: text("value_json").notNull(),
  sensitivity: text("sensitivity", { enum: ["public", "admin_only", "encrypted_secret"] })
    .notNull()
    .default("admin_only"),
  updatedById: text("updated_by_id")
    .notNull()
    .references(() => users.id, { onDelete: "restrict" }),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const auditLogs = sqliteTable(
  "audit_logs",
  {
    id: text("id").primaryKey(),
    actorId: text("actor_id").references(() => users.id, { onDelete: "set null" }),
    action: text("action").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id"),
    result: text("result", { enum: ["success", "denied", "failure"] }).notNull(),
    metadataJson: text("metadata_json"),
    requestId: text("request_id"),
    ipHash: text("ip_hash"),
    expiresAt: text("expires_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("idx_audit_logs_actor_created").on(table.actorId, table.createdAt),
    index("idx_audit_logs_entity_created").on(
      table.entityType,
      table.entityId,
      table.createdAt,
    ),
    index("idx_audit_logs_action_created").on(table.action, table.createdAt),
  ],
);

export const backupRecords = sqliteTable(
  "backup_records",
  {
    id: text("id").primaryKey(),
    triggeredById: text("triggered_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    trigger: text("trigger", { enum: ["manual", "scheduled"] }).notNull(),
    scope: text("scope", { enum: ["database", "files", "full"] }).notNull(),
    status: text("status", { enum: ["queued", "running", "completed", "failed", "verified"] })
      .notNull()
      .default("queued"),
    storageKey: text("storage_key"),
    checksum: text("checksum"),
    byteSize: integer("byte_size"),
    errorCode: text("error_code"),
    errorMessage: text("error_message"),
    expiresAt: text("expires_at"),
    deletedAt: text("deleted_at"),
    startedAt: text("started_at"),
    finishedAt: text("finished_at"),
    verifiedAt: text("verified_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("idx_backup_records_status_created").on(table.status, table.createdAt),
    index("idx_backup_records_created").on(table.createdAt),
    index("idx_backup_records_expires").on(table.expiresAt, table.deletedAt),
  ],
);

export const exportJobs = sqliteTable(
  "export_jobs",
  {
    id: text("id").primaryKey(),
    requestedById: text("requested_by_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    reportType: text("report_type").notNull(),
    format: text("format", { enum: ["xlsx", "pdf", "csv"] }).notNull(),
    scopeJson: text("scope_json").notNull(),
    filterJson: text("filter_json").notNull().default("{}"),
    snapshotAt: text("snapshot_at").notNull(),
    dataSnapshotJson: text("data_snapshot_json").notNull().default("{}"),
    missingDataJson: text("missing_data_json").notNull().default("[]"),
    timezone: text("timezone").notNull().default("Asia/Macau"),
    reportVersion: text("report_version").notNull().default("v1"),
    status: text("status", { enum: ["queued", "running", "completed", "failed", "cancelled"] })
      .notNull()
      .default("queued"),
    storageKey: text("storage_key"),
    sha256: text("sha256"),
    byteSize: integer("byte_size"),
    attemptCount: integer("attempt_count").notNull().default(0),
    errorCode: text("error_code"),
    errorMessage: text("error_message"),
    correlationId: text("correlation_id").notNull(),
    expiresAt: text("expires_at"),
    deletedAt: text("deleted_at"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    startedAt: text("started_at"),
    finishedAt: text("finished_at"),
  },
  (table) => [
    index("idx_export_jobs_requester_created").on(table.requestedById, table.createdAt),
    index("idx_export_jobs_status_created").on(table.status, table.createdAt),
    index("idx_export_jobs_expires").on(table.expiresAt, table.status),
  ],
);
